[package]
name = "forge-cli"
description = "Ligne de commande de forge."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "forge"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
forge-codegen.workspace = true
forge-schema.workspace = true
serde_json.workspace = true

[lints]
workspace = true
